/**
 * popup向background传递的指令
 *
 * 这个文件会被popup和background引用
 */
export default {
  /**
   * 开始屏幕录像
   */
  ON_RECORD: 'ON_RECORD',
  ON_DISPLAY: 'ON_DISPLAY',
  /**
   * 停止屏幕录像
   */
  STOP_RECORD: 'STOP_RECORD',

  GET_STATUS_URL: 'GET_STATUS_URL',
  GET_STORY_LIST: 'GET_STORY_LIST',
  DELETE_STORY: 'DELETE_STORY',

  SYNC_RECORDING_STATUS: 'SYNC_RECORDING_STATUS',
  GET_STORY_AND_ITS_EVENTS: 'GET_STORY_AND_ITS_EVENTS',
  DISPLAY_COMPONENT_DESTROYED: 'DISPLAY_COMPONENT_DESTROYED',
  R_U_STILL_ALIVE: 'R_U_STILL_ALIVE',
  GET_CHROME: 'GET_CHROME',
  GET_STORY_AND_ITS_IMAGES: 'GET_STORY_AND_ITS_IMAGES',
  UPDATE_STORY: 'UPDATE_STORY',
  GO_DEMO: 'GO_DEMO'
}
